name: Build
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 3 * * *'
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        base_flavour: ["xenial", "bionic", "focal", "focal-2.23-locales", "focal-2.23-locpath"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2 # this is currently using @Ben Fritsch Dockerhub login account
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v3
      with:
        context: dod-locales-base-${{ matrix.base_flavour }}
        push: true
        tags: heroku/dod-locale-base:${{ matrix.base_flavour }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
